# Setup
title:               GSoC 2020
tagline:             'BeagleBoard.org'
description:         'This website is created for keeping track of the Development of "Cape compatibility layer for BeagleBone Black and BeagleBone AI" project.'
url:                 https://lorforlinux.github.io
baseurl:             /GSoC2020_BeagleBoard.org
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Deepak Khatri
  url:               https://lorforlinux.github.io/
  email:             deepaklorkhatri7@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1
week:                 12
status:              "Finalizing compatibility code!"
google_analytics_id: #UA-XXXX-Y
